- name: Add the br_netfilter module
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - br_netfilter
    - ip_vs
    - ip_vs_rr
    - ip_vs_wrr
    - ip_vs_sh
    - nf_conntrack
- name: install docker library
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
- name: add dcoker yum repo
  shell: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
- name: install docker
  yum:
    name:
      - docker-ce-19.03.8-3.el7.x86_64
      - docker-ce-cli-19.03.8-3.el7.x86_64
- name: create docker config dir
  file:
    path: /etc/docker
    state: directory
- name: setting docker daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
- name: start docker
  systemd:
    name: docker
    state: started
    enabled: yes
- name: add kubeadm yum repo
  template:
    src: kubeadm.repo.j2
    dest: /etc/yum.repos.d/kubeadm.repo
- name: install kubeadm
  yum:
    name:
      - kubeadm-1.18.3
      - kubectl-1.18.3
      - kubelet-1.18.3
    state: present
- name: copy images shell
  template:
    src: images.sh.j2
    dest: /root/images.sh
    mode: 0755
- name: pull images
  shell: /root/images.sh
