---
- name: create backup yum repo describe
  ansible.builtin.file:
    path: /etc/yum.repos.d/back
    state: directory
- name: backup yum repo
  shell: mv /etc/yum.repos.d/*.repo /etc/yum.repo.d/back/
- name: get aliyun yum repo
  ansible.builtin.get_url:
    url: http://mirrors.aliyun.com/repo/Centos-7.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
- name: get aliyun yum repo eple
  ansible.builtin.get_url:
    url: http://mirrors.aliyun.com/repo/epel-7.repo
    dest: /etc/yum.repos.d/epel-7.repo
- name: yum update install
  yum:
    name:
      - conntrack 
      - ntpdate 
      - ntp 
      - ipvsadm 
      - jq 
      - iptables 
      - curl 
      - sysstat 
      - libseccomp 
      - wget 
      - net-tools 
      - git
    state: present
- name: stop firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
- name: install iptables-server
  yum: 
    name:
      - iptables-services
    state: present
- name: start iptables
  ansible.builtin.systemd:
    name: iptables
    state: started
    enabled: yes
- name: setting iptables rules
  shell: iptables -F && service iptables save
- name: copy kubernetes system
  template:
    src: kubernetes.conf.j2
    dest: /etc/sysctl.d/kubernetes.conf
- name: apply kubernetes.conf
  shell: sysctl -p
- name: stop postfix
  ansible.builtin.systemd:
    name: postfix
    state: stopped
    enabled: no
- name: install kernel-ml-4.19
  yum:
    name: http://tools.file.irybd.com/kernel-ml-devel-4.19.12-1.el7.elrepo.x86_64.rpm
    state: present
- name: install kernel-ml-devel-4.19
  yum:
    name: http://tools.file.irybd.com/kernel-ml-4.19.12-1.el7.elrepo.x86_64.rpm
    state: present
- name: setting grub kernel
  shell: grub2-set-default "CentOS Linux (4.19.12-1.el7.elrepo.x86_64) 7 (Core)"
- name: reboot system
  reboot:
    reboot_timeout: 3600
- name: remove old kernel
  yum:
    name:
      - kernel-3.10.0
      - kernel-tools-libs
      - kernel-tools
    state: removed
